services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    env_file:
      - .env
    volumes:
      - mongo-data:/data/dev
      - mongo-data:/data/test

volumes:
  mongo-data:
