services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    env_file:
      - .env.test
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
